"""cambie nombre tabla de producto_model a productos


Revision ID: 260fd454e9e5
Revises: 6a2bbefb9bc9
Create Date: 2024-11-29 20:33:04.664673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260fd454e9e5'
down_revision = '6a2bbefb9bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.rename_table
    op.rename_table('producto_model','productos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('productos','producto_model')
    # ### end Alembic commands ###
