"""agregue columna fecha_vencimiento

Revision ID: 6a2bbefb9bc9
Revises: 6bb2b852b970
Create Date: 2024-11-29 20:23:38.616987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2bbefb9bc9'
down_revision = '6bb2b852b970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_model', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('fecha_vencimiento')

    # ### end Alembic commands ###
